"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderUpload = renderUpload;
var renderTs_1 = require("./renderTs");
function renderUpload() {
    var html = "\n    <div class=\"container mx-auto p-6\">\n      <div class=\"w-full max-w-3xl mx-auto bg-white p-6 rounded-2xl shadow-lg\">\n        <h2 class=\"text-2xl font-bold text-gray-800 mb-6 text-center\">Formul\u00E1rio de Envio</h2>\n\n        <form action=\"\">\n          <div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\">\n            <div class=\"col-span-2\">\n              <label for=\"uploadArquivo\" class=\"block mb-2 font-medium text-gray-700\">Arquivo</label>\n              <div class=\"border border-gray-300 rounded-lg flex items-center\">\n                <label for=\"uploadArquivo\" class=\"text-blue-600 font-semibold border-r border-gray-300 px-3 py-2 cursor-pointer hover:bg-blue-50\">\n                  Escolher\n                </label>\n                <input type=\"file\" id=\"uploadArquivo\" class=\"flex-1 px-3 py-2 text-sm text-gray-700\" />\n              </div>\n            </div>\n\n            <div>\n              <label for=\"texto\" class=\"block mb-2 font-medium text-gray-700\">Texto</label>\n              <input type=\"text\" id=\"texto\" placeholder=\"Digite algo...\" \n                class=\"border border-gray-300 rounded-lg px-3 py-2 w-full focus:ring-2 focus:ring-blue-500 focus:outline-none\" />\n            </div>\n\n            <div>\n              <label for=\"turmaSelect\" class=\"block mb-2 font-medium text-gray-700\">Escolha sua turma</label>\n              <select id=\"turmaSelect\" class=\"border border-gray-300 rounded-lg px-3 py-2 w-full focus:ring-2 focus:ring-blue-500 focus:outline-none\">\n                <option value=\"nenhuma\">Nenhuma Selecionada</option>\n                <option value=\"turma1\">#Turma1</option>\n                <option value=\"turma2\">#Turma2</option>\n                <option value=\"turma3\">#Turma3</option>\n              </select>\n            </div>\n\n            <div>\n              <label for=\"data\" class=\"block mb-2 font-medium text-gray-700\">Escolha a data</label>\n              <input type=\"date\" id=\"data\" \n                class=\"border border-gray-300 rounded-lg px-3 py-2 w-full focus:ring-2 focus:ring-blue-500 focus:outline-none\" />\n            </div>\n          </div>\n\n          <div class=\"flex justify-end\">\n            <button \n              type=\"submit\" \n              class=\"bg-blue-600 text-white px-6 py-2 rounded-lg font-medium \n                    hover:bg-blue-700 transition duration-200 shadow-sm\"\n            >\n              Enviar\n            </button>\n          </div>\n        </form>\n      </div>\n    </div>\n  ";
    (0, renderTs_1.attConteudoarea)(html);
}
;
